# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""HistoryActionLabelUpdate
An action representing a Label being updated.

    HistoryActionLabelUpdate(;
        id=nothing,
        entity_type=nothing,
        action=nothing,
    )

    - id::Int64 : The ID of the entity referenced.
    - entity_type::String : The type of entity referenced.
    - action::String : The action of the entity referenced.
"""
Base.@kwdef mutable struct HistoryActionLabelUpdate <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    entity_type::Union{Nothing, String} = nothing
    action::Union{Nothing, String} = nothing

    function HistoryActionLabelUpdate(id, entity_type, action, )
        OpenAPI.validate_property(HistoryActionLabelUpdate, Symbol("id"), id)
        OpenAPI.validate_property(HistoryActionLabelUpdate, Symbol("entity_type"), entity_type)
        OpenAPI.validate_property(HistoryActionLabelUpdate, Symbol("action"), action)
        return new(id, entity_type, action, )
    end
end # type HistoryActionLabelUpdate

const _property_types_HistoryActionLabelUpdate = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("entity_type")=>"String", Symbol("action")=>"String", )
OpenAPI.property_type(::Type{ HistoryActionLabelUpdate }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_HistoryActionLabelUpdate[name]))}

function check_required(o::HistoryActionLabelUpdate)
    o.id === nothing && (return false)
    o.entity_type === nothing && (return false)
    o.action === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ HistoryActionLabelUpdate }, name::Symbol, val)

    if name === Symbol("id")
        OpenAPI.validate_param(name, "HistoryActionLabelUpdate", :format, val, "int64")
    end


    if name === Symbol("action")
        OpenAPI.validate_param(name, "HistoryActionLabelUpdate", :enum, val, ["update"])
    end

end
