# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""UpdateComment

    UpdateComment(;
        text=nothing,
    )

    - text::String : The updated comment text.
"""
Base.@kwdef mutable struct UpdateComment <: OpenAPI.APIModel
    text::Union{Nothing, String} = nothing

    function UpdateComment(text, )
        OpenAPI.validate_property(UpdateComment, Symbol("text"), text)
        return new(text, )
    end
end # type UpdateComment

const _property_types_UpdateComment = Dict{Symbol,String}(Symbol("text")=>"String", )
OpenAPI.property_type(::Type{ UpdateComment }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_UpdateComment[name]))}

function check_required(o::UpdateComment)
    o.text === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ UpdateComment }, name::Symbol, val)

end
