# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""StoryHistoryChangeOldNewBool
True if the Story has archived, otherwise false.

    StoryHistoryChangeOldNewBool(;
        old=nothing,
        new=nothing,
    )

    - old::Bool : The old value.
    - new::Bool : The new value.
"""
Base.@kwdef mutable struct StoryHistoryChangeOldNewBool <: OpenAPI.APIModel
    old::Union{Nothing, Bool} = nothing
    new::Union{Nothing, Bool} = nothing

    function StoryHistoryChangeOldNewBool(old, new, )
        OpenAPI.validate_property(StoryHistoryChangeOldNewBool, Symbol("old"), old)
        OpenAPI.validate_property(StoryHistoryChangeOldNewBool, Symbol("new"), new)
        return new(old, new, )
    end
end # type StoryHistoryChangeOldNewBool

const _property_types_StoryHistoryChangeOldNewBool = Dict{Symbol,String}(Symbol("old")=>"Bool", Symbol("new")=>"Bool", )
OpenAPI.property_type(::Type{ StoryHistoryChangeOldNewBool }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_StoryHistoryChangeOldNewBool[name]))}

function check_required(o::StoryHistoryChangeOldNewBool)
    true
end

function OpenAPI.validate_property(::Type{ StoryHistoryChangeOldNewBool }, name::Symbol, val)


end
