# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""KeyResultValue
The starting value of the Key Result.

    KeyResultValue(;
        numeric_value=nothing,
        boolean_value=nothing,
    )

    - numeric_value::String : The numeric value, as a decimal string. No more than two decimal places are allowed.
    - boolean_value::Bool : The boolean value.
"""
Base.@kwdef mutable struct KeyResultValue <: OpenAPI.APIModel
    numeric_value::Union{Nothing, String} = nothing
    boolean_value::Union{Nothing, Bool} = nothing

    function KeyResultValue(numeric_value, boolean_value, )
        OpenAPI.validate_property(KeyResultValue, Symbol("numeric_value"), numeric_value)
        OpenAPI.validate_property(KeyResultValue, Symbol("boolean_value"), boolean_value)
        return new(numeric_value, boolean_value, )
    end
end # type KeyResultValue

const _property_types_KeyResultValue = Dict{Symbol,String}(Symbol("numeric_value")=>"String", Symbol("boolean_value")=>"Bool", )
OpenAPI.property_type(::Type{ KeyResultValue }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_KeyResultValue[name]))}

function check_required(o::KeyResultValue)
    true
end

function OpenAPI.validate_property(::Type{ KeyResultValue }, name::Symbol, val)


end
