# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""UpdateLinkedFile

    UpdateLinkedFile(;
        description=nothing,
        story_id=nothing,
        name=nothing,
        thumbnail_url=nothing,
        type=nothing,
        size=nothing,
        uploader_id=nothing,
        url=nothing,
    )

    - description::String : The description of the file.
    - story_id::Int64 : The ID of the linked story.
    - name::String : The name of the file.
    - thumbnail_url::String : The URL of the thumbnail, if the integration provided it.
    - type::String : The integration type of the file (e.g. google, dropbox, box).
    - size::Int64 : The filesize, if the integration provided it.
    - uploader_id::String : The UUID of the member that uploaded the file.
    - url::String : The URL of linked file.
"""
Base.@kwdef mutable struct UpdateLinkedFile <: OpenAPI.APIModel
    description::Union{Nothing, String} = nothing
    story_id::Union{Nothing, Int64} = nothing
    name::Union{Nothing, String} = nothing
    thumbnail_url::Union{Nothing, String} = nothing
    type::Union{Nothing, String} = nothing
    size::Union{Nothing, Int64} = nothing
    uploader_id::Union{Nothing, String} = nothing
    url::Union{Nothing, String} = nothing

    function UpdateLinkedFile(description, story_id, name, thumbnail_url, type, size, uploader_id, url, )
        OpenAPI.validate_property(UpdateLinkedFile, Symbol("description"), description)
        OpenAPI.validate_property(UpdateLinkedFile, Symbol("story_id"), story_id)
        OpenAPI.validate_property(UpdateLinkedFile, Symbol("name"), name)
        OpenAPI.validate_property(UpdateLinkedFile, Symbol("thumbnail_url"), thumbnail_url)
        OpenAPI.validate_property(UpdateLinkedFile, Symbol("type"), type)
        OpenAPI.validate_property(UpdateLinkedFile, Symbol("size"), size)
        OpenAPI.validate_property(UpdateLinkedFile, Symbol("uploader_id"), uploader_id)
        OpenAPI.validate_property(UpdateLinkedFile, Symbol("url"), url)
        return new(description, story_id, name, thumbnail_url, type, size, uploader_id, url, )
    end
end # type UpdateLinkedFile

const _property_types_UpdateLinkedFile = Dict{Symbol,String}(Symbol("description")=>"String", Symbol("story_id")=>"Int64", Symbol("name")=>"String", Symbol("thumbnail_url")=>"String", Symbol("type")=>"String", Symbol("size")=>"Int64", Symbol("uploader_id")=>"String", Symbol("url")=>"String", )
OpenAPI.property_type(::Type{ UpdateLinkedFile }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_UpdateLinkedFile[name]))}

function check_required(o::UpdateLinkedFile)
    true
end

function OpenAPI.validate_property(::Type{ UpdateLinkedFile }, name::Symbol, val)

    if name === Symbol("description")
        OpenAPI.validate_param(name, "UpdateLinkedFile", :maxLength, val, 512)
    end

    if name === Symbol("story_id")
        OpenAPI.validate_param(name, "UpdateLinkedFile", :format, val, "int64")
    end

    if name === Symbol("name")
        OpenAPI.validate_param(name, "UpdateLinkedFile", :minLength, val, 1)
    end

    if name === Symbol("thumbnail_url")
        OpenAPI.validate_param(name, "UpdateLinkedFile", :maxLength, val, 2048)
        OpenAPI.validate_param(name, "UpdateLinkedFile", :pattern, val, r"^https?:\/\/.+$")
    end

    if name === Symbol("type")
        OpenAPI.validate_param(name, "UpdateLinkedFile", :enum, val, ["google", "url", "dropbox", "box", "onedrive"])
    end


    if name === Symbol("size")
        OpenAPI.validate_param(name, "UpdateLinkedFile", :format, val, "int64")
    end

    if name === Symbol("uploader_id")
        OpenAPI.validate_param(name, "UpdateLinkedFile", :format, val, "uuid")
    end

    if name === Symbol("url")
        OpenAPI.validate_param(name, "UpdateLinkedFile", :maxLength, val, 2048)
        OpenAPI.validate_param(name, "UpdateLinkedFile", :pattern, val, r"^https?:\/\/.+$")
    end
end
