# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ObjectiveSearchResults
The results of the Objective search query.

    ObjectiveSearchResults(;
        total=nothing,
        data=nothing,
        next=nothing,
    )

    - total::Int64 : The total number of matches for the search query. The first 1000 matches can be paged through via the API.
    - data::Vector{ObjectiveSearchResult} : A list of search results.
    - next::String : The URL path and query string for the next page of search results.
"""
Base.@kwdef mutable struct ObjectiveSearchResults <: OpenAPI.APIModel
    total::Union{Nothing, Int64} = nothing
    data::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{ObjectiveSearchResult} }
    next::Union{Nothing, String} = nothing

    function ObjectiveSearchResults(total, data, next, )
        OpenAPI.validate_property(ObjectiveSearchResults, Symbol("total"), total)
        OpenAPI.validate_property(ObjectiveSearchResults, Symbol("data"), data)
        OpenAPI.validate_property(ObjectiveSearchResults, Symbol("next"), next)
        return new(total, data, next, )
    end
end # type ObjectiveSearchResults

const _property_types_ObjectiveSearchResults = Dict{Symbol,String}(Symbol("total")=>"Int64", Symbol("data")=>"Vector{ObjectiveSearchResult}", Symbol("next")=>"String", )
OpenAPI.property_type(::Type{ ObjectiveSearchResults }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ObjectiveSearchResults[name]))}

function check_required(o::ObjectiveSearchResults)
    o.total === nothing && (return false)
    o.data === nothing && (return false)
    o.next === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ ObjectiveSearchResults }, name::Symbol, val)

    if name === Symbol("total")
        OpenAPI.validate_param(name, "ObjectiveSearchResults", :format, val, "int64")
    end


end
