# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""RemoveCustomFieldParams

    RemoveCustomFieldParams(;
        field_id=nothing,
    )

    - field_id::String : The unique public ID for the CustomField.
"""
Base.@kwdef mutable struct RemoveCustomFieldParams <: OpenAPI.APIModel
    field_id::Union{Nothing, String} = nothing

    function RemoveCustomFieldParams(field_id, )
        OpenAPI.validate_property(RemoveCustomFieldParams, Symbol("field_id"), field_id)
        return new(field_id, )
    end
end # type RemoveCustomFieldParams

const _property_types_RemoveCustomFieldParams = Dict{Symbol,String}(Symbol("field_id")=>"String", )
OpenAPI.property_type(::Type{ RemoveCustomFieldParams }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_RemoveCustomFieldParams[name]))}

function check_required(o::RemoveCustomFieldParams)
    o.field_id === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ RemoveCustomFieldParams }, name::Symbol, val)

    if name === Symbol("field_id")
        OpenAPI.validate_param(name, "RemoveCustomFieldParams", :format, val, "uuid")
    end
end
