# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""CreateCommentComment

    CreateCommentComment(;
        text=nothing,
        author_id=nothing,
        created_at=nothing,
        updated_at=nothing,
        external_id=nothing,
    )

    - text::String : The comment text.
    - author_id::String : The Member ID of the Comment&#39;s author. Defaults to the user identified by the API token.
    - created_at::ZonedDateTime : Defaults to the time/date the comment is created, but can be set to reflect another date.
    - updated_at::ZonedDateTime : Defaults to the time/date the comment is last updated, but can be set to reflect another date.
    - external_id::String : This field can be set to another unique ID. In the case that the comment has been imported from another tool, the ID in the other tool can be indicated here.
"""
Base.@kwdef mutable struct CreateCommentComment <: OpenAPI.APIModel
    text::Union{Nothing, String} = nothing
    author_id::Union{Nothing, String} = nothing
    created_at::Union{Nothing, ZonedDateTime} = nothing
    updated_at::Union{Nothing, ZonedDateTime} = nothing
    external_id::Union{Nothing, String} = nothing

    function CreateCommentComment(text, author_id, created_at, updated_at, external_id, )
        OpenAPI.validate_property(CreateCommentComment, Symbol("text"), text)
        OpenAPI.validate_property(CreateCommentComment, Symbol("author_id"), author_id)
        OpenAPI.validate_property(CreateCommentComment, Symbol("created_at"), created_at)
        OpenAPI.validate_property(CreateCommentComment, Symbol("updated_at"), updated_at)
        OpenAPI.validate_property(CreateCommentComment, Symbol("external_id"), external_id)
        return new(text, author_id, created_at, updated_at, external_id, )
    end
end # type CreateCommentComment

const _property_types_CreateCommentComment = Dict{Symbol,String}(Symbol("text")=>"String", Symbol("author_id")=>"String", Symbol("created_at")=>"ZonedDateTime", Symbol("updated_at")=>"ZonedDateTime", Symbol("external_id")=>"String", )
OpenAPI.property_type(::Type{ CreateCommentComment }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_CreateCommentComment[name]))}

function check_required(o::CreateCommentComment)
    o.text === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ CreateCommentComment }, name::Symbol, val)

    if name === Symbol("text")
        OpenAPI.validate_param(name, "CreateCommentComment", :maxLength, val, 100000)
        OpenAPI.validate_param(name, "CreateCommentComment", :minLength, val, 1)
    end

    if name === Symbol("author_id")
        OpenAPI.validate_param(name, "CreateCommentComment", :format, val, "uuid")
    end

    if name === Symbol("created_at")
        OpenAPI.validate_param(name, "CreateCommentComment", :format, val, "date-time")
    end

    if name === Symbol("updated_at")
        OpenAPI.validate_param(name, "CreateCommentComment", :format, val, "date-time")
    end

    if name === Symbol("external_id")
        OpenAPI.validate_param(name, "CreateCommentComment", :maxLength, val, 128)
    end
end
