# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""WorkflowState
Workflow State is any of the at least 3 columns. Workflow States correspond to one of 3 types: Unstarted, Started, or Done.

    WorkflowState(;
        description=nothing,
        entity_type=nothing,
        color=nothing,
        verb=nothing,
        name=nothing,
        global_id=nothing,
        num_stories=nothing,
        type=nothing,
        updated_at=nothing,
        id=nothing,
        num_story_templates=nothing,
        position=nothing,
        created_at=nothing,
    )

    - description::String : The description of what sort of Stories belong in that Workflow state.
    - entity_type::String : A string description of this resource.
    - color::String : The hex color for this Workflow State.
    - verb::String : The verb that triggers a move to that Workflow State when making VCS commits.
    - name::String : The Workflow State&#39;s name.
    - global_id::String
    - num_stories::Int64 : The number of Stories currently in that Workflow State.
    - type::String : The type of Workflow State (Unstarted, Started, or Finished)
    - updated_at::ZonedDateTime : When the Workflow State was last updated.
    - id::Int64 : The unique ID of the Workflow State.
    - num_story_templates::Int64 : The number of Story Templates associated with that Workflow State.
    - position::Int64 : The position that the Workflow State is in, starting with 0 at the left.
    - created_at::ZonedDateTime : The time/date the Workflow State was created.
"""
Base.@kwdef mutable struct WorkflowState <: OpenAPI.APIModel
    description::Union{Nothing, String} = nothing
    entity_type::Union{Nothing, String} = nothing
    color::Union{Nothing, String} = nothing
    verb::Union{Nothing, String} = nothing
    name::Union{Nothing, String} = nothing
    global_id::Union{Nothing, String} = nothing
    num_stories::Union{Nothing, Int64} = nothing
    type::Union{Nothing, String} = nothing
    updated_at::Union{Nothing, ZonedDateTime} = nothing
    id::Union{Nothing, Int64} = nothing
    num_story_templates::Union{Nothing, Int64} = nothing
    position::Union{Nothing, Int64} = nothing
    created_at::Union{Nothing, ZonedDateTime} = nothing

    function WorkflowState(description, entity_type, color, verb, name, global_id, num_stories, type, updated_at, id, num_story_templates, position, created_at, )
        OpenAPI.validate_property(WorkflowState, Symbol("description"), description)
        OpenAPI.validate_property(WorkflowState, Symbol("entity_type"), entity_type)
        OpenAPI.validate_property(WorkflowState, Symbol("color"), color)
        OpenAPI.validate_property(WorkflowState, Symbol("verb"), verb)
        OpenAPI.validate_property(WorkflowState, Symbol("name"), name)
        OpenAPI.validate_property(WorkflowState, Symbol("global_id"), global_id)
        OpenAPI.validate_property(WorkflowState, Symbol("num_stories"), num_stories)
        OpenAPI.validate_property(WorkflowState, Symbol("type"), type)
        OpenAPI.validate_property(WorkflowState, Symbol("updated_at"), updated_at)
        OpenAPI.validate_property(WorkflowState, Symbol("id"), id)
        OpenAPI.validate_property(WorkflowState, Symbol("num_story_templates"), num_story_templates)
        OpenAPI.validate_property(WorkflowState, Symbol("position"), position)
        OpenAPI.validate_property(WorkflowState, Symbol("created_at"), created_at)
        return new(description, entity_type, color, verb, name, global_id, num_stories, type, updated_at, id, num_story_templates, position, created_at, )
    end
end # type WorkflowState

const _property_types_WorkflowState = Dict{Symbol,String}(Symbol("description")=>"String", Symbol("entity_type")=>"String", Symbol("color")=>"String", Symbol("verb")=>"String", Symbol("name")=>"String", Symbol("global_id")=>"String", Symbol("num_stories")=>"Int64", Symbol("type")=>"String", Symbol("updated_at")=>"ZonedDateTime", Symbol("id")=>"Int64", Symbol("num_story_templates")=>"Int64", Symbol("position")=>"Int64", Symbol("created_at")=>"ZonedDateTime", )
OpenAPI.property_type(::Type{ WorkflowState }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_WorkflowState[name]))}

function check_required(o::WorkflowState)
    o.description === nothing && (return false)
    o.entity_type === nothing && (return false)
    o.verb === nothing && (return false)
    o.name === nothing && (return false)
    o.global_id === nothing && (return false)
    o.num_stories === nothing && (return false)
    o.type === nothing && (return false)
    o.updated_at === nothing && (return false)
    o.id === nothing && (return false)
    o.num_story_templates === nothing && (return false)
    o.position === nothing && (return false)
    o.created_at === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ WorkflowState }, name::Symbol, val)



    if name === Symbol("color")
        OpenAPI.validate_param(name, "WorkflowState", :format, val, "css-color")
    end
    if name === Symbol("color")
        OpenAPI.validate_param(name, "WorkflowState", :minLength, val, 1)
        OpenAPI.validate_param(name, "WorkflowState", :pattern, val, r"^#[a-fA-F0-9]{6}$")
    end




    if name === Symbol("num_stories")
        OpenAPI.validate_param(name, "WorkflowState", :format, val, "int64")
    end


    if name === Symbol("updated_at")
        OpenAPI.validate_param(name, "WorkflowState", :format, val, "date-time")
    end

    if name === Symbol("id")
        OpenAPI.validate_param(name, "WorkflowState", :format, val, "int64")
    end

    if name === Symbol("num_story_templates")
        OpenAPI.validate_param(name, "WorkflowState", :format, val, "int64")
    end

    if name === Symbol("position")
        OpenAPI.validate_param(name, "WorkflowState", :format, val, "int64")
    end

    if name === Symbol("created_at")
        OpenAPI.validate_param(name, "WorkflowState", :format, val, "date-time")
    end
end
