# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""MaxSearchResultsExceededError
Error returned when total maximum supported results have been reached.

    MaxSearchResultsExceededError(;
        error=nothing,
        message=nothing,
        var"maximum-results"=nothing,
    )

    - error::String : The name for this type of error, &#x60;maximum-results-exceeded&#x60;
    - message::String : An explanatory message: \&quot;A maximum of 1000 search results are supported.\&quot;
    - var"maximum-results"::Int64 : The maximum number of search results supported, &#x60;1000&#x60;
"""
Base.@kwdef mutable struct MaxSearchResultsExceededError <: OpenAPI.APIModel
    error::Union{Nothing, String} = nothing
    message::Union{Nothing, String} = nothing
    var"maximum-results"::Union{Nothing, Int64} = nothing

    function MaxSearchResultsExceededError(error, message, var"maximum-results", )
        OpenAPI.validate_property(MaxSearchResultsExceededError, Symbol("error"), error)
        OpenAPI.validate_property(MaxSearchResultsExceededError, Symbol("message"), message)
        OpenAPI.validate_property(MaxSearchResultsExceededError, Symbol("maximum-results"), var"maximum-results")
        return new(error, message, var"maximum-results", )
    end
end # type MaxSearchResultsExceededError

const _property_types_MaxSearchResultsExceededError = Dict{Symbol,String}(Symbol("error")=>"String", Symbol("message")=>"String", Symbol("maximum-results")=>"Int64", )
OpenAPI.property_type(::Type{ MaxSearchResultsExceededError }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_MaxSearchResultsExceededError[name]))}

function check_required(o::MaxSearchResultsExceededError)
    o.error === nothing && (return false)
    o.message === nothing && (return false)
    o.var"maximum-results" === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ MaxSearchResultsExceededError }, name::Symbol, val)

    if name === Symbol("error")
        OpenAPI.validate_param(name, "MaxSearchResultsExceededError", :enum, val, ["maximum-results-exceeded"])
    end



    if name === Symbol("maximum-results")
        OpenAPI.validate_param(name, "MaxSearchResultsExceededError", :enum, val, [1000])
    end

end
