# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""UpdateStoryComment

    UpdateStoryComment(;
        text=nothing,
    )

    - text::String : The updated comment text.
"""
Base.@kwdef mutable struct UpdateStoryComment <: OpenAPI.APIModel
    text::Union{Nothing, String} = nothing

    function UpdateStoryComment(text, )
        OpenAPI.validate_property(UpdateStoryComment, Symbol("text"), text)
        return new(text, )
    end
end # type UpdateStoryComment

const _property_types_UpdateStoryComment = Dict{Symbol,String}(Symbol("text")=>"String", )
OpenAPI.property_type(::Type{ UpdateStoryComment }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_UpdateStoryComment[name]))}

function check_required(o::UpdateStoryComment)
    o.text === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ UpdateStoryComment }, name::Symbol, val)

    if name === Symbol("text")
        OpenAPI.validate_param(name, "UpdateStoryComment", :maxLength, val, 100000)
    end
end
