# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""CreateGroup

    CreateGroup(;
        description=nothing,
        member_ids=nothing,
        workflow_ids=nothing,
        name=nothing,
        mention_name=nothing,
        color=nothing,
        color_key=nothing,
        display_icon_id=nothing,
    )

    - description::String : The description of the Group.
    - member_ids::Vector{String} : The Member ids to add to this Group.
    - workflow_ids::Vector{Int64} : The Workflow ids to add to the Group.
    - name::String : The name of this Group.
    - mention_name::String : The mention name of this Group.
    - color::String : The color you wish to use for the Group in the system.
    - color_key::String : The color key you wish to use for the Group in the system.
    - display_icon_id::String : The Icon id for the avatar of this Group.
"""
Base.@kwdef mutable struct CreateGroup <: OpenAPI.APIModel
    description::Union{Nothing, String} = nothing
    member_ids::Union{Nothing, Vector{String}} = nothing
    workflow_ids::Union{Nothing, Vector{Int64}} = nothing
    name::Union{Nothing, String} = nothing
    mention_name::Union{Nothing, String} = nothing
    color::Union{Nothing, String} = nothing
    color_key::Union{Nothing, String} = nothing
    display_icon_id::Union{Nothing, String} = nothing

    function CreateGroup(description, member_ids, workflow_ids, name, mention_name, color, color_key, display_icon_id, )
        OpenAPI.validate_property(CreateGroup, Symbol("description"), description)
        OpenAPI.validate_property(CreateGroup, Symbol("member_ids"), member_ids)
        OpenAPI.validate_property(CreateGroup, Symbol("workflow_ids"), workflow_ids)
        OpenAPI.validate_property(CreateGroup, Symbol("name"), name)
        OpenAPI.validate_property(CreateGroup, Symbol("mention_name"), mention_name)
        OpenAPI.validate_property(CreateGroup, Symbol("color"), color)
        OpenAPI.validate_property(CreateGroup, Symbol("color_key"), color_key)
        OpenAPI.validate_property(CreateGroup, Symbol("display_icon_id"), display_icon_id)
        return new(description, member_ids, workflow_ids, name, mention_name, color, color_key, display_icon_id, )
    end
end # type CreateGroup

const _property_types_CreateGroup = Dict{Symbol,String}(Symbol("description")=>"String", Symbol("member_ids")=>"Vector{String}", Symbol("workflow_ids")=>"Vector{Int64}", Symbol("name")=>"String", Symbol("mention_name")=>"String", Symbol("color")=>"String", Symbol("color_key")=>"String", Symbol("display_icon_id")=>"String", )
OpenAPI.property_type(::Type{ CreateGroup }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_CreateGroup[name]))}

function check_required(o::CreateGroup)
    o.name === nothing && (return false)
    o.mention_name === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ CreateGroup }, name::Symbol, val)

    if name === Symbol("description")
        OpenAPI.validate_param(name, "CreateGroup", :maxLength, val, 4096)
    end

    if name === Symbol("member_ids")
        OpenAPI.validate_param(name, "CreateGroup", :uniqueItems, val, true)
    end


    if name === Symbol("name")
        OpenAPI.validate_param(name, "CreateGroup", :maxLength, val, 63)
        OpenAPI.validate_param(name, "CreateGroup", :minLength, val, 1)
    end

    if name === Symbol("mention_name")
        OpenAPI.validate_param(name, "CreateGroup", :maxLength, val, 63)
        OpenAPI.validate_param(name, "CreateGroup", :minLength, val, 1)
    end

    if name === Symbol("color")
        OpenAPI.validate_param(name, "CreateGroup", :format, val, "css-color")
    end
    if name === Symbol("color")
        OpenAPI.validate_param(name, "CreateGroup", :minLength, val, 1)
        OpenAPI.validate_param(name, "CreateGroup", :pattern, val, r"^#[a-fA-F0-9]{6}$")
    end

    if name === Symbol("color_key")
        OpenAPI.validate_param(name, "CreateGroup", :enum, val, ["blue", "purple", "midnight-blue", "orange", "yellow-green", "brass", "gray", "fuchsia", "yellow", "pink", "sky-blue", "green", "red", "black", "slate", "turquoise"])
    end


    if name === Symbol("display_icon_id")
        OpenAPI.validate_param(name, "CreateGroup", :format, val, "uuid")
    end
end
