# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""EpicSearchResults
The results of the Epic search query.

    EpicSearchResults(;
        total=nothing,
        data=nothing,
        next=nothing,
    )

    - total::Int64 : The total number of matches for the search query. The first 1000 matches can be paged through via the API.
    - data::Vector{EpicSearchResult} : A list of search results.
    - next::String : The URL path and query string for the next page of search results.
"""
Base.@kwdef mutable struct EpicSearchResults <: OpenAPI.APIModel
    total::Union{Nothing, Int64} = nothing
    data::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{EpicSearchResult} }
    next::Union{Nothing, String} = nothing

    function EpicSearchResults(total, data, next, )
        OpenAPI.validate_property(EpicSearchResults, Symbol("total"), total)
        OpenAPI.validate_property(EpicSearchResults, Symbol("data"), data)
        OpenAPI.validate_property(EpicSearchResults, Symbol("next"), next)
        return new(total, data, next, )
    end
end # type EpicSearchResults

const _property_types_EpicSearchResults = Dict{Symbol,String}(Symbol("total")=>"Int64", Symbol("data")=>"Vector{EpicSearchResult}", Symbol("next")=>"String", )
OpenAPI.property_type(::Type{ EpicSearchResults }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_EpicSearchResults[name]))}

function check_required(o::EpicSearchResults)
    o.total === nothing && (return false)
    o.data === nothing && (return false)
    o.next === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ EpicSearchResults }, name::Symbol, val)

    if name === Symbol("total")
        OpenAPI.validate_param(name, "EpicSearchResults", :format, val, "int64")
    end


end
