# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""SyncedItem
The synced item for the story.

    SyncedItem(;
        external_id=nothing,
        url=nothing,
    )

    - external_id::String : The id used to reference an external entity.
    - url::String : The url to the external entity.
"""
Base.@kwdef mutable struct SyncedItem <: OpenAPI.APIModel
    external_id::Union{Nothing, String} = nothing
    url::Union{Nothing, String} = nothing

    function SyncedItem(external_id, url, )
        OpenAPI.validate_property(SyncedItem, Symbol("external_id"), external_id)
        OpenAPI.validate_property(SyncedItem, Symbol("url"), url)
        return new(external_id, url, )
    end
end # type SyncedItem

const _property_types_SyncedItem = Dict{Symbol,String}(Symbol("external_id")=>"String", Symbol("url")=>"String", )
OpenAPI.property_type(::Type{ SyncedItem }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_SyncedItem[name]))}

function check_required(o::SyncedItem)
    o.external_id === nothing && (return false)
    o.url === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ SyncedItem }, name::Symbol, val)


end
