# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""HistoryActionStoryDelete
An action representing a Story being deleted.

    HistoryActionStoryDelete(;
        id=nothing,
        entity_type=nothing,
        action=nothing,
        name=nothing,
        story_type=nothing,
    )

    - id::Int64 : The ID of the entity referenced.
    - entity_type::String : The type of entity referenced.
    - action::String : The action of the entity referenced.
    - name::String : The name of the Story.
    - story_type::String : The type of Story; either feature, bug, or chore.
"""
Base.@kwdef mutable struct HistoryActionStoryDelete <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    entity_type::Union{Nothing, String} = nothing
    action::Union{Nothing, String} = nothing
    name::Union{Nothing, String} = nothing
    story_type::Union{Nothing, String} = nothing

    function HistoryActionStoryDelete(id, entity_type, action, name, story_type, )
        OpenAPI.validate_property(HistoryActionStoryDelete, Symbol("id"), id)
        OpenAPI.validate_property(HistoryActionStoryDelete, Symbol("entity_type"), entity_type)
        OpenAPI.validate_property(HistoryActionStoryDelete, Symbol("action"), action)
        OpenAPI.validate_property(HistoryActionStoryDelete, Symbol("name"), name)
        OpenAPI.validate_property(HistoryActionStoryDelete, Symbol("story_type"), story_type)
        return new(id, entity_type, action, name, story_type, )
    end
end # type HistoryActionStoryDelete

const _property_types_HistoryActionStoryDelete = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("entity_type")=>"String", Symbol("action")=>"String", Symbol("name")=>"String", Symbol("story_type")=>"String", )
OpenAPI.property_type(::Type{ HistoryActionStoryDelete }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_HistoryActionStoryDelete[name]))}

function check_required(o::HistoryActionStoryDelete)
    o.id === nothing && (return false)
    o.entity_type === nothing && (return false)
    o.action === nothing && (return false)
    o.name === nothing && (return false)
    o.story_type === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ HistoryActionStoryDelete }, name::Symbol, val)

    if name === Symbol("id")
        OpenAPI.validate_param(name, "HistoryActionStoryDelete", :format, val, "int64")
    end


    if name === Symbol("action")
        OpenAPI.validate_param(name, "HistoryActionStoryDelete", :enum, val, ["delete"])
    end



    if name === Symbol("story_type")
        OpenAPI.validate_param(name, "HistoryActionStoryDelete", :enum, val, ["feature", "chore", "bug"])
    end

end
