# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""TypedStoryLink
The type of Story Link. The string can be subject or object. 

    TypedStoryLink(;
        entity_type=nothing,
        object_id=nothing,
        verb=nothing,
        type=nothing,
        updated_at=nothing,
        id=nothing,
        subject_id=nothing,
        subject_workflow_state_id=nothing,
        created_at=nothing,
    )

    - entity_type::String : A string description of this resource.
    - object_id::Int64 : The ID of the object Story.
    - verb::String : How the subject Story acts on the object Story. This can be \&quot;blocks\&quot;, \&quot;duplicates\&quot;, or \&quot;relates to\&quot;.
    - type::String : This indicates whether the Story is the subject or object in the Story Link.
    - updated_at::ZonedDateTime : The time/date when the Story Link was last updated.
    - id::Int64 : The unique identifier of the Story Link.
    - subject_id::Int64 : The ID of the subject Story.
    - subject_workflow_state_id::Int64 : The workflow state of the \&quot;subject\&quot; story.
    - created_at::ZonedDateTime : The time/date when the Story Link was created.
"""
Base.@kwdef mutable struct TypedStoryLink <: OpenAPI.APIModel
    entity_type::Union{Nothing, String} = nothing
    object_id::Union{Nothing, Int64} = nothing
    verb::Union{Nothing, String} = nothing
    type::Union{Nothing, String} = nothing
    updated_at::Union{Nothing, ZonedDateTime} = nothing
    id::Union{Nothing, Int64} = nothing
    subject_id::Union{Nothing, Int64} = nothing
    subject_workflow_state_id::Union{Nothing, Int64} = nothing
    created_at::Union{Nothing, ZonedDateTime} = nothing

    function TypedStoryLink(entity_type, object_id, verb, type, updated_at, id, subject_id, subject_workflow_state_id, created_at, )
        OpenAPI.validate_property(TypedStoryLink, Symbol("entity_type"), entity_type)
        OpenAPI.validate_property(TypedStoryLink, Symbol("object_id"), object_id)
        OpenAPI.validate_property(TypedStoryLink, Symbol("verb"), verb)
        OpenAPI.validate_property(TypedStoryLink, Symbol("type"), type)
        OpenAPI.validate_property(TypedStoryLink, Symbol("updated_at"), updated_at)
        OpenAPI.validate_property(TypedStoryLink, Symbol("id"), id)
        OpenAPI.validate_property(TypedStoryLink, Symbol("subject_id"), subject_id)
        OpenAPI.validate_property(TypedStoryLink, Symbol("subject_workflow_state_id"), subject_workflow_state_id)
        OpenAPI.validate_property(TypedStoryLink, Symbol("created_at"), created_at)
        return new(entity_type, object_id, verb, type, updated_at, id, subject_id, subject_workflow_state_id, created_at, )
    end
end # type TypedStoryLink

const _property_types_TypedStoryLink = Dict{Symbol,String}(Symbol("entity_type")=>"String", Symbol("object_id")=>"Int64", Symbol("verb")=>"String", Symbol("type")=>"String", Symbol("updated_at")=>"ZonedDateTime", Symbol("id")=>"Int64", Symbol("subject_id")=>"Int64", Symbol("subject_workflow_state_id")=>"Int64", Symbol("created_at")=>"ZonedDateTime", )
OpenAPI.property_type(::Type{ TypedStoryLink }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_TypedStoryLink[name]))}

function check_required(o::TypedStoryLink)
    o.entity_type === nothing && (return false)
    o.object_id === nothing && (return false)
    o.verb === nothing && (return false)
    o.type === nothing && (return false)
    o.updated_at === nothing && (return false)
    o.id === nothing && (return false)
    o.subject_id === nothing && (return false)
    o.subject_workflow_state_id === nothing && (return false)
    o.created_at === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ TypedStoryLink }, name::Symbol, val)


    if name === Symbol("object_id")
        OpenAPI.validate_param(name, "TypedStoryLink", :format, val, "int64")
    end



    if name === Symbol("updated_at")
        OpenAPI.validate_param(name, "TypedStoryLink", :format, val, "date-time")
    end

    if name === Symbol("id")
        OpenAPI.validate_param(name, "TypedStoryLink", :format, val, "int64")
    end

    if name === Symbol("subject_id")
        OpenAPI.validate_param(name, "TypedStoryLink", :format, val, "int64")
    end

    if name === Symbol("subject_workflow_state_id")
        OpenAPI.validate_param(name, "TypedStoryLink", :format, val, "int64")
    end

    if name === Symbol("created_at")
        OpenAPI.validate_param(name, "TypedStoryLink", :format, val, "date-time")
    end
end
