# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""CreateStories

    CreateStories(;
        stories=nothing,
    )

    - stories::Vector{CreateStoryParams} : An array of stories to be created.
"""
Base.@kwdef mutable struct CreateStories <: OpenAPI.APIModel
    stories::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{CreateStoryParams} }

    function CreateStories(stories, )
        OpenAPI.validate_property(CreateStories, Symbol("stories"), stories)
        return new(stories, )
    end
end # type CreateStories

const _property_types_CreateStories = Dict{Symbol,String}(Symbol("stories")=>"Vector{CreateStoryParams}", )
OpenAPI.property_type(::Type{ CreateStories }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_CreateStories[name]))}

function check_required(o::CreateStories)
    o.stories === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ CreateStories }, name::Symbol, val)

end
