# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""StoryHistoryChangeOldNewStr
A timestamp that represents the Story&#39;s deadline.

    StoryHistoryChangeOldNewStr(;
        old=nothing,
        new=nothing,
    )

    - old::String : The old value.
    - new::String : The new value.
"""
Base.@kwdef mutable struct StoryHistoryChangeOldNewStr <: OpenAPI.APIModel
    old::Union{Nothing, String} = nothing
    new::Union{Nothing, String} = nothing

    function StoryHistoryChangeOldNewStr(old, new, )
        OpenAPI.validate_property(StoryHistoryChangeOldNewStr, Symbol("old"), old)
        OpenAPI.validate_property(StoryHistoryChangeOldNewStr, Symbol("new"), new)
        return new(old, new, )
    end
end # type StoryHistoryChangeOldNewStr

const _property_types_StoryHistoryChangeOldNewStr = Dict{Symbol,String}(Symbol("old")=>"String", Symbol("new")=>"String", )
OpenAPI.property_type(::Type{ StoryHistoryChangeOldNewStr }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_StoryHistoryChangeOldNewStr[name]))}

function check_required(o::StoryHistoryChangeOldNewStr)
    true
end

function OpenAPI.validate_property(::Type{ StoryHistoryChangeOldNewStr }, name::Symbol, val)


end
