# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""StoryHistoryChangeOldNewInt
The estimate value for the Story

    StoryHistoryChangeOldNewInt(;
        old=nothing,
        new=nothing,
    )

    - old::Int64 : The old value.
    - new::Int64 : The new value.
"""
Base.@kwdef mutable struct StoryHistoryChangeOldNewInt <: OpenAPI.APIModel
    old::Union{Nothing, Int64} = nothing
    new::Union{Nothing, Int64} = nothing

    function StoryHistoryChangeOldNewInt(old, new, )
        OpenAPI.validate_property(StoryHistoryChangeOldNewInt, Symbol("old"), old)
        OpenAPI.validate_property(StoryHistoryChangeOldNewInt, Symbol("new"), new)
        return new(old, new, )
    end
end # type StoryHistoryChangeOldNewInt

const _property_types_StoryHistoryChangeOldNewInt = Dict{Symbol,String}(Symbol("old")=>"Int64", Symbol("new")=>"Int64", )
OpenAPI.property_type(::Type{ StoryHistoryChangeOldNewInt }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_StoryHistoryChangeOldNewInt[name]))}

function check_required(o::StoryHistoryChangeOldNewInt)
    true
end

function OpenAPI.validate_property(::Type{ StoryHistoryChangeOldNewInt }, name::Symbol, val)

    if name === Symbol("old")
        OpenAPI.validate_param(name, "StoryHistoryChangeOldNewInt", :format, val, "int64")
    end

    if name === Symbol("new")
        OpenAPI.validate_param(name, "StoryHistoryChangeOldNewInt", :format, val, "int64")
    end
end
