# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""BasicWorkspaceInfo

    BasicWorkspaceInfo(;
        url_slug=nothing,
        estimate_scale=nothing,
    )

    - url_slug::String
    - estimate_scale::Vector{Int64}
"""
Base.@kwdef mutable struct BasicWorkspaceInfo <: OpenAPI.APIModel
    url_slug::Union{Nothing, String} = nothing
    estimate_scale::Union{Nothing, Vector{Int64}} = nothing

    function BasicWorkspaceInfo(url_slug, estimate_scale, )
        OpenAPI.validate_property(BasicWorkspaceInfo, Symbol("url_slug"), url_slug)
        OpenAPI.validate_property(BasicWorkspaceInfo, Symbol("estimate_scale"), estimate_scale)
        return new(url_slug, estimate_scale, )
    end
end # type BasicWorkspaceInfo

const _property_types_BasicWorkspaceInfo = Dict{Symbol,String}(Symbol("url_slug")=>"String", Symbol("estimate_scale")=>"Vector{Int64}", )
OpenAPI.property_type(::Type{ BasicWorkspaceInfo }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_BasicWorkspaceInfo[name]))}

function check_required(o::BasicWorkspaceInfo)
    o.url_slug === nothing && (return false)
    o.estimate_scale === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ BasicWorkspaceInfo }, name::Symbol, val)


end
