# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""CreateObjective

    CreateObjective(;
        name=nothing,
        description=nothing,
        state=nothing,
        started_at_override=nothing,
        completed_at_override=nothing,
        categories=nothing,
    )

    - name::String : The name of the Objective.
    - description::String : The Objective&#39;s description.
    - state::String : The workflow state that the Objective is in.
    - started_at_override::ZonedDateTime : A manual override for the time/date the Objective was started.
    - completed_at_override::ZonedDateTime : A manual override for the time/date the Objective was completed.
    - categories::Vector{CreateCategoryParams} : An array of IDs of Categories attached to the Objective.
"""
Base.@kwdef mutable struct CreateObjective <: OpenAPI.APIModel
    name::Union{Nothing, String} = nothing
    description::Union{Nothing, String} = nothing
    state::Union{Nothing, String} = nothing
    started_at_override::Union{Nothing, ZonedDateTime} = nothing
    completed_at_override::Union{Nothing, ZonedDateTime} = nothing
    categories::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{CreateCategoryParams} }

    function CreateObjective(name, description, state, started_at_override, completed_at_override, categories, )
        OpenAPI.validate_property(CreateObjective, Symbol("name"), name)
        OpenAPI.validate_property(CreateObjective, Symbol("description"), description)
        OpenAPI.validate_property(CreateObjective, Symbol("state"), state)
        OpenAPI.validate_property(CreateObjective, Symbol("started_at_override"), started_at_override)
        OpenAPI.validate_property(CreateObjective, Symbol("completed_at_override"), completed_at_override)
        OpenAPI.validate_property(CreateObjective, Symbol("categories"), categories)
        return new(name, description, state, started_at_override, completed_at_override, categories, )
    end
end # type CreateObjective

const _property_types_CreateObjective = Dict{Symbol,String}(Symbol("name")=>"String", Symbol("description")=>"String", Symbol("state")=>"String", Symbol("started_at_override")=>"ZonedDateTime", Symbol("completed_at_override")=>"ZonedDateTime", Symbol("categories")=>"Vector{CreateCategoryParams}", )
OpenAPI.property_type(::Type{ CreateObjective }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_CreateObjective[name]))}

function check_required(o::CreateObjective)
    o.name === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ CreateObjective }, name::Symbol, val)

    if name === Symbol("name")
        OpenAPI.validate_param(name, "CreateObjective", :maxLength, val, 256)
        OpenAPI.validate_param(name, "CreateObjective", :minLength, val, 1)
    end

    if name === Symbol("description")
        OpenAPI.validate_param(name, "CreateObjective", :maxLength, val, 100000)
    end

    if name === Symbol("state")
        OpenAPI.validate_param(name, "CreateObjective", :enum, val, ["in progress", "to do", "done"])
    end


    if name === Symbol("started_at_override")
        OpenAPI.validate_param(name, "CreateObjective", :format, val, "date-time")
    end

    if name === Symbol("completed_at_override")
        OpenAPI.validate_param(name, "CreateObjective", :format, val, "date-time")
    end

end
