# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""DeleteStories

    DeleteStories(;
        story_ids=nothing,
    )

    - story_ids::Vector{Int64} : An array of IDs of Stories to delete.
"""
Base.@kwdef mutable struct DeleteStories <: OpenAPI.APIModel
    story_ids::Union{Nothing, Vector{Int64}} = nothing

    function DeleteStories(story_ids, )
        OpenAPI.validate_property(DeleteStories, Symbol("story_ids"), story_ids)
        return new(story_ids, )
    end
end # type DeleteStories

const _property_types_DeleteStories = Dict{Symbol,String}(Symbol("story_ids")=>"Vector{Int64}", )
OpenAPI.property_type(::Type{ DeleteStories }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_DeleteStories[name]))}

function check_required(o::DeleteStories)
    o.story_ids === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ DeleteStories }, name::Symbol, val)

    if name === Symbol("story_ids")
        OpenAPI.validate_param(name, "DeleteStories", :uniqueItems, val, true)
    end
end
