# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ObjectiveStats
A group of calculated values for this Objective.

    ObjectiveStats(;
        average_cycle_time=nothing,
        average_lead_time=nothing,
        num_related_documents=nothing,
    )

    - average_cycle_time::Int64 : The average cycle time (in seconds) of completed stories in this Objective.
    - average_lead_time::Int64 : The average lead time (in seconds) of completed stories in this Objective.
    - num_related_documents::Int64 : The number of related documents to this Objective.
"""
Base.@kwdef mutable struct ObjectiveStats <: OpenAPI.APIModel
    average_cycle_time::Union{Nothing, Int64} = nothing
    average_lead_time::Union{Nothing, Int64} = nothing
    num_related_documents::Union{Nothing, Int64} = nothing

    function ObjectiveStats(average_cycle_time, average_lead_time, num_related_documents, )
        OpenAPI.validate_property(ObjectiveStats, Symbol("average_cycle_time"), average_cycle_time)
        OpenAPI.validate_property(ObjectiveStats, Symbol("average_lead_time"), average_lead_time)
        OpenAPI.validate_property(ObjectiveStats, Symbol("num_related_documents"), num_related_documents)
        return new(average_cycle_time, average_lead_time, num_related_documents, )
    end
end # type ObjectiveStats

const _property_types_ObjectiveStats = Dict{Symbol,String}(Symbol("average_cycle_time")=>"Int64", Symbol("average_lead_time")=>"Int64", Symbol("num_related_documents")=>"Int64", )
OpenAPI.property_type(::Type{ ObjectiveStats }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ObjectiveStats[name]))}

function check_required(o::ObjectiveStats)
    o.num_related_documents === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ ObjectiveStats }, name::Symbol, val)

    if name === Symbol("average_cycle_time")
        OpenAPI.validate_param(name, "ObjectiveStats", :format, val, "int64")
    end

    if name === Symbol("average_lead_time")
        OpenAPI.validate_param(name, "ObjectiveStats", :format, val, "int64")
    end

    if name === Symbol("num_related_documents")
        OpenAPI.validate_param(name, "ObjectiveStats", :format, val, "int64")
    end
end
